### ISSUE TITLE
How to clear colors and styles?

### ISSUE THREAD

**Issue by dhruvkb** [jam1garner/owo-colors#110]
I use `colorize` in a project and was seeing if `owo-colors` might be a better fit. However `owo-colors` does not provide a `clear()` function, [like `colorize` does](https://docs.rs/colored/2.0.0/colored/trait.Colorize.html#tymethod.clear).

What is the recommended approach for clearing all formatting applied to a given string?

**Comment by sunshowers** [comment]
Maybe https://docs.rs/owo-colors/latest/owo_colors/struct.Style.html#method.default_color ?

**Comment by dhruvkb** [comment]
`default_color` sets only the foreground color to the default so it's not the same as `clear` which 

- resets the FG color
- resets the BG color
- removes all styles (like underline or bold etc.)
