### ISSUE TITLE
Implementation of `std::slice::Join` for `owo_colors::Styled`

### ISSUE THREAD

**Issue by tecc** [jam1garner/owo-colors#111]
It's just a nice thing to have - instead of writing
```rust
strings
    .iter()
    .map(|string| string.style(some_style).to_string())
    .collect::<Vec<_>>()
    .join(", ")
 ```

It could instead be the following
```rust
strings
    .iter()
    .map(|string| string.style(some_style))
    .collect::<Vec<_>>()
    .join(", ")
 ```
 
 Sure, it's a tiny thing, but it does make such code look less clean to me with the former option.

**Comment by jam1garner** [comment]
Pretty sure this just flat out isn't possible--correct me if I'm wrong but the implementation of Join requires returning a borrowed slice. owo-colors doesn't have any pre-rendered buffer of the colored text, the coloration and text are separately stored even for `Styled`, so there's no existing slice to borrow.

Feel free to reopen if I'm wrong
