### ISSUE TITLE
Inlined colors

### ISSUE THREAD

**Issue by eugenesvk** [jam1garner/owo-colors#112]
Would it be possible to support a more dense inline style of coloring similar to this python function
`print_color("Command {c.b}{name}{c.d} {c.r}not found{c.d}")`
where `c.b` would be blue and `c.d` would reset to default, ideally with customizable styles so you could have `c.bb` for blue bold instead of having to do `{}, name.blue().bold();`

**Comment by jam1garner** [comment]
This is a design I considered in the past before deciding that there's no reason for this to exist inside owo-colors--it could simply be a macro implemented in a separate library that expands to the equivalent owo-colors code.

If such a library existed and began to gain popularity, I would be willing to integrate it into owo-colors (similarly to how `clap 2 -> structopt + clap 2 -> clap 3` was handled).

**Comment by eugenesvk** [comment]
The reason is for the users of owo to have access to a much better input format without having to spend time looking up yet another library - which could only happen is they're even be aware that such an improvement is possible as the `"{}",var` is much more widespread 

(clap is way more popular, so the chances of that happening here is lower)
