### ISSUE TITLE
security advisory triggered because of `supports-color`

### ISSUE THREAD

**Issue by OmarTawfik** [jam1garner/owo-colors#114]
Advisory: https://github.com/advisories/GHSA-g98v-hv3f-hcfr

Dependency looks like it is already fixed in https://github.com/jam1garner/owo-colors/commit/abb63524634712d3c562ac0685a93f5e19ac5130

But the fix was never released. I wonder if we can release `3.6.0` to fix this?

Thanks.

**Comment by sunshowers** [comment]
The issue here is that updating supports-color would be a breaking change.

**Comment by sunshowers** [comment]
> Should someone go and fix atty?

So if we want to not bump a major version, I think what we could do is expose an alternative feature `supports-colors-2` which pulls in v2 of supports-color, and turn it into an optional feature just like `supports-color` is. That way `atty` isn't going to be pulled in if `supports-colors-2` is used.

However, tools that aren't smart enough to filter by features enabled are going to alert on this. I'm not sure whether dependabot is one of them (I've generally been disappointed at dependabot to be honest). I will say that if `supports-color` isn't enabled, the Cargo.lock file won't have supports-colors or atty in it (unless something else pulls those crates in).

**Comment by sunshowers** [comment]
#115 is my attempt to fix this.

**Comment by OmarTawfik** [comment]
Thanks @sunshowers !
