### ISSUE TITLE
New release broke my program

### ISSUE THREAD

**Issue by dylan-bowker** [jam1garner/owo-colors#12]
Hey I'm not able to compile my program anymore. 

```
error[E0658]: const generics are unstable
   --> C:\Users\YYY\.cargo\registry\src\github.com-1ecc6299db9ec823\owo-colors-1.4.2\src\lib.rs:306:25
    |
306 |     fn fg_rgb<'a, const R: u8, const G: u8, const B: u8>(
    |                         ^
    |
    = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information
```

**Comment by jam1garner** [comment]
The new minor release bumps the MSRV to 1.51 (latest stable). For early versions, 1.3 is recommended. If you don't mind using newer Rust, install 1.51 using the following command:

```
rustup update stable
```

**Comment by SirWindfield** [comment]
Isn't this (in theory) a breaking change? 

Besides that, I'll open a PR to add a notice for the MSRV if you are OK with it, CSS colors coming tmrw probably.

**Comment by jam1garner** [comment]
From what I've seen, community consensus is MSRV changes are only considered a minor bump. I can definitely understand the concern, however I imagine it's likely a non-issue in practice. If it proves itself to be a problem, I will consider yanking 1.4 and re-releasing as 2.0.

**Comment by SirWindfield** [comment]
Nah, not me, I was just curious on what your opinion on it was, I didn't know that the community handles it that way, it's fine for me :)
