### ISSUE TITLE
Can't build documentation on stable Rust

### ISSUE THREAD

**Issue by sunshowers** [jam1garner/owo-colors#38]
If I try building documentation for a crate that depends on owo-colors on Rust 1.57, I get:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /opt/cargo/registry/src/github.com-1ecc6299db9ec823/owo-colors-3.1.0/src/lib.rs:72:37
   |
72 | #![cfg_attr(all(doc, not(doctest)), feature(doc_cfg))]
   |                                     ^^^^^^^^^^^^^^^^
```

I think this might need to be gated to docs-rs somehow?

**Comment by sunshowers** [comment]
Example in CI: https://github.com/facebookincubator/cargo-guppy/runs/4414663526?check_suite_focus=true

**Comment by jam1garner** [comment]
Yep, I agree, gating behind a docs.rs-only feature is the right solution :+1:
