### ISSUE TITLE
Converting between `u8` and `XtermColors`

### ISSUE THREAD

**Issue by LordMZTE** [jam1garner/owo-colors#42]
Something that at the moment is very annoying to do with owo-colors is coloring a string when given a Xterm color code in the form of a u8, as the only ways to convert between a u8 and a XtermColors struct are to use unsound code to transmute it (the enum isn't `#[repr(u8)]`) or a 255 line long match expression. It would be great if conversion functionality was added.

**Comment by jam1garner** [comment]
@LordMZTE pushed in owo_colors v3.2.0, which is now on crates.io
