### ISSUE TITLE
Spelling mistake in type names

### ISSUE THREAD

**Issue by Wilfred** [jam1garner/owo-colors#46]
```
type DynEquivelant = ansi_colors::AnsiColors;
const DYN_EQUIVELANT: Self::DynEquivelant = ansi_colors::AnsiColors::$color;
```

This should be `DynEquivalent` and so on.

I guess it'd be a breaking change to fix this though.

**Comment by jam1garner** [comment]
oops >_> thank you for pointing this out, I'll try and make sure this gets fixed the next time I'm making breaking changes

**Comment by jam1garner** [comment]
Looks like I'm going to be doing a 4.0 release soon so I'll try to include this

**Comment by jam1garner** [comment]
Finallyyyy
