### ISSUE TITLE
Update of supports-color in 3.6.0 is breaking

### ISSUE THREAD

**Issue by Emilgardis** [jam1garner/owo-colors#82]
Hi!

The latest update from `3.5.0` -> `3.6.0` should've been `3.5.0` -> `4.0.0` due to https://github.com/jam1garner/owo-colors/commit/abb63524634712d3c562ac0685a93f5e19ac5130 and https://github.com/jam1garner/owo-colors/blob/509f6e68cfe0ce7e062837f60b33b0d9e0e5e374/src/lib.rs#L471

See cross-rs/cross#1177

**Comment by Emilgardis** [comment]
The release should be janked and released as `4.0.0`

**Comment by jam1garner** [comment]
Ugh I'm so sorry, did not pay attention enough when bumping the version. Will yank now and  take some time to consider whether I'm going to do a 4.x bump or just stick to supports-color 1.x.
