### ISSUE TITLE
Question about performance with static strings

### ISSUE THREAD

**Issue by SirWindfield** [jam1garner/owo-colors#9]
Hey!

I've written https://github.com/SirWindfield/ansi-colors-macro-rs as I couldn't find any colouring library that does not allocate a new String for each message they create, either through `format!` or by simply calling `push` on a String for each ANSI color code fragment.

My project does expand the static string into ANSI escape codes at compile-time. Speaking of efficiency and performance, is your crate the same/better/worse? `println!`, `write!` and the likes seem to not allocate new memory which should eliminate the allocation problem I always faced.

Interface-wise yours feels more natural but I explicitly tried to get coloured messages into `const` declarations, and no crate could do that. Is it possible with yours? Due to the fact that you rely on `Display` as well my guess would be no :(.

**Comment by jam1garner** [comment]
Hmmmmm ok so I definitely think it's possible for my design to work in a const context, especially if special-casing for static strings. It doesn't *exactly* work currently, although I'm pretty sure it somewhat is possible trivially.

```rust
const TEST: &dyn Display = &"test".blue();
```

*should* work, although I'd need to mark some stuff const. While it is `&dyn Trait` (which would imply indirection), I believe in this case the vtable would be optimized out so long as you only directly display it. This is really just a hack to deal with the fact `impl Trait` can't be used for constants.

If you're looking for actually baking the strings themselves in, it might be a bit more complicated, although I thiiiiink technically possible on stable (doing string concatenation in const fn is... Hard atm. typically requires some gross bits of going between bytes and strings, although I've done similar stuff for my const generic Rgb implementation, which uses compile-time string formatting tricks).

Fwiw, I don't think actually compiling down to the string itself is that useful if you plan on using it with display down the road, however I'd definitely be willing to help you out if you'd mind elaborating on your use case I'll see what I can do \:) I think if anything owo-colors' strategy should be in the best position for a library to handle const contexts.

If all your concern is just "does this cause allocations or have other notable runtime costs over hand-writing the strings", the answer is nope! The way owo-colors works is just by encoding color into the type if possible, so there is no need to allocate, it just knows which color to print at compile-time.

**Comment by jam1garner** [comment]
Ok oops, dumb mistake I made above: the reason owo-colors doesn't currently support const contexts is because the interface is based around using an extension trait (that's why you can just do `.blue()` on anything that implements an std formatting trait). However trait const methods are still unstable, so while I could definitely make it so they are const behind a "nightly" crate feature, I'd prefer I only have to do so if there's a good motivating use case.

I think it's also worth noting @SirWindfield that:

```rust
const MY_STRING: &str = "this is some text etc etc";

fn main() {
    println("{}", MY_STRING.blue());
}
```

Will:
1. only encode that it's blue at a type-system level. (more on this in a second)
2. not store any information aside from "this is some text etc etc" as data in your binary
3. never copy MY_STRING at runtime, it is only directly output to stdout
4. not allocate anywhere in the above program

Think of it as something like the following:

```rust
#[repr(transparent)]
struct BlueStr(&'static str);

impl Display for BlueStr {
    // ouput ansi blue escape sequence, then the string, then output a "clear style" sequence
}
```

rather than actually make a blue copy of the &str, the &str is treated *identically* in memory as a normal reference to a const string is. The only difference is once it goes to display it, it goes "OH this isn't an &str, this is a BLUE &str" and outputs the ansi escape sequences needed.

If you're baking multiple strings of the same color into your binary, this approach will honestly likely have a lower cost than just baking in the pre-colored string. This is because the strings of the same color will (a) share a display function, good for the instruction cache usage and (b) there won't be a bunch of copies of the ansi escape sequences... which is good for data cache usage. While this is honestly too small a difference to easily benchmark, I think it's worth noting that in all likelihood, if you're trying to push it past this point, the perf benefits will be lost in the noise of everything else (esp since you're likely doing I/O if you're using these strings!)

**Comment by SirWindfield** [comment]
Although I have been using Rust for some time now, I am still not entirely knowledgeable on all aspects of it. I never really read into the whole dynamic dispatch thing.

> I think it's also worth noting @SirWindfield that:...

I do understand this. The string reference is entirely the same, the "feature" lies inside the `Display` implementation of the extension trait that just pushes the ANSI code before pushing the string itself to the formatter.

I always thought that this allocates though. As the `Display` implementation relies on `write!`, which expects a `dyn Write` as it's first argument. I guess `println!` is special in that it does directly write to stdout without buffering, thus not allocating. I am not entirely sure though.

Maybe I can bring in why I was looking for it. The crates that I saw did actually use `format!` for example. That way, they definitely did allocate. I wanted some `const` messages in one of my crates that are decorated with colors to make them more readable. They never change, so I was looking for something that can "calculate" the formatting at compile-time instead of relying on `format!` and friends.

To give a specific use-case and why I wrote `ansi-colors-macro`. I do re-use a lot of status symbols in the form of Emojis across my CLIs I write. Instead of copy-pasting them each time I published them to a crate. I wanted to include a colored version without having to rely on another crate for coloring them. I couldn't find any crate that did it at compile-time using `const fn` so the symbols get colored directly without me having to actually decide on what coloring library I want to use. [Here](https://github.com/SirWindfield/terminal-log-symbols-rs/blob/cf069ba0ab37432d26a65f7fb1eb979581ddeab8/src/lib.rs#L24) an example on what the crate looks like. Not much in it, but maybe it helps to understand what I meant.

The libraries, as of today, are not `const`-friendly so I can't really use them if my goal is to create five const items resembling some Emojis.

**Comment by jam1garner** [comment]
Honestly I would personally not bother having the coloring in the const item itself imo? but if you find that something you prefer, go for it. I personally recommend having only the string be in the constant, while the actual coloration is marked wherever it is displayed, such as in this example from above:

```rust
const MY_STRING: &str = "this is some text etc etc";

fn main() {
    println("{}", MY_STRING.blue());
}
```

possibly even handling the color in a function:

```
const MY_STRING: &str = "this is some text etc etc";

fn print_error(error: &str) {
    println("{}", error.red());
}

fn main() {
    print_error(MY_STRING);
}
```

>  I do understand this. The string reference is entirely the same, the "feature" lies inside the Display implementation of the extension trait that just pushes the ANSI code before pushing the string itself to the formatter.

The "pushing" is merely writing things in order. Think of it like this:

```
const COLOR_BLUE: &str = /*...*/;
const MY_STRING: &str = "this is some text etc etc";
const CLEAR_STYLE: &str = /*...*/;

fn main() {
    write_to_stdout(COLOR_BLUE);
    write_to_stdout(MY_STRING);
    write_to_stdout(CLEAR_STYLE);
}
```

the actual text isn't pushed into an allocated buffer, they're just output in-order.

**Comment by SirWindfield** [comment]
> Honestly I would personally not bother having the coloring in the const item itself imo?

I do get that and I think the same. I just thought that I would probably always use the colored version, so I might as well just put it into the crate to not have to bother with it anymore when using it.

Thanks for taking your time and explaining the stuff to me! Of all coloring crates, I do think this is one of the more complete ones, especially since it has support for all the std traits like `UpperHex` for example.

**Comment by jam1garner** [comment]
> I do get that and I think the same. I just thought that I would probably always use the colored version, so I might as well just put it into the crate to not have to bother with it anymore when using it.

Yep, totally get how you came to that conclusion.

> Thanks for taking your time and explaining the stuff to me! Of all coloring crates, I do think this is one of the more complete ones, especially since it has support for all the std traits like UpperHex for example.

Thank you! I'm glad you like it. Feel free to reopen this issue if needed
